---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Develop:
    - Github:
        icon: github.svg
        href: https://github.com
        description: https://github.com

- News:
    - Google News:
        icon: google.svg
        href: https://news.google.com
        description: https://news.google.com
